spring.application.name=Bread_project


#server port
server.port=8181

#oracle settings
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=bread_site
spring.datasource.password=1234

#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=com.example.Bread_project
mybatis.configuration.jdbc-type-for-null=NULL

#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tkavkf30409
spring.mail.password=wshognsmtmopuaxh
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true

#jwt settings
jwt.secret-key=abcdefghijklmnopqrstuvwxyz12345678901234567890
jwt.expire-hour=1

